security:

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|img|js)/
            security: false
   
            # https://symfony.com/doc/current/security/form_login_setup.html