swiftmailer:
    disable_delivery:  false
    transport: sendmail
    auth_mode: login
    port: 465
    host: mail.ericdelangle.fr
    username: info@ericdelangle.fr
    password: junfanpol76
    #spool: { type: 'memory' }
